### ISSUE TITLE
Stopping a (global?) Subscription?

### ISSUE THREAD

**Issue by aadamsx** [mondora/asteroid#117]
There's a way to subscribe (only globally?):

> // Use real-time collections
asteroid.subscribe("tasksPublication");

But is there a way to stop?

> let handler = Meteor.subscribe('items');
...
// subscription no longer necessary
handler.stop();

**Comment by davidebianchi** [comment]
There is the `unsubscribe ` method provided by  the`subscriptions` mixin. This is what you are searching?

**Comment by aadamsx** [comment]
Thank you!
