### ISSUE TITLE
Disconnecting from Remote Meteor App?

### ISSUE THREAD

**Issue by aadamsx** [mondora/asteroid#118]
We can connect to Remote Meteor App like so:

> import {createClass} from "asteroid";

const Asteroid = createClass();
// Connect to a Meteor backend
const asteroid = new Asteroid({
    endpoint: "ws://localhost:3000/websocket"
});

But what about disconnecting?

**Comment by davidebianchi** [comment]
The available methods are in the README. There is the disconnect method provided by `ddp` mixin, It is this what you are looking for?

**Comment by aadamsx** [comment]
Thanks!
