### ISSUE TITLE
when is v3 going to release?

### ISSUE THREAD

**Issue by hatelove85911** [mondora/asteroid#124]
when is v3 going to release?
I tried using asteroid with meteor 1.5.1, but the socket connection doesn't work.

**Comment by Falieson** [comment]
I've been making my stack with react & meteor 1.6 to run jest tests with node 8. I'm almost using typescript.
If meteor 1.5.1 doesn't work, I doubt 1.6 will (I haven't tried it yet). 
Is there a particular reason @hatelove85911 you need meteor 1.5.1 for the backend to use w/ asteroid? I've been using this as an example: https://github.com/juliancwirko/react-redux-webpack-meteor which uses `METEOR@1.4.2.3` . If its just a meteor mongo ddp connection you're going for, is there a reason for a more recent version of meteor? 

[meteor 1.5](https://blog.meteor.com/announcing-meteor-1-5-1-b65ecddf955b) brought isobulid dynamic module loading but that's a frontend thing (handled by webpack's code splitting) and SSR.

meteor 1.5.2 is a security update (maybe a good reason for a fix to the package)

[meteor 1.6](https://github.com/meteor/meteor/pull/8728) upgrades node8 from node4 and removes babel settings for server code

**Comment by Falieson** [comment]
@hatelove85911 I tried upgrading @juliancwirko 's demo to 1.5.1 and it worked fine. 
https://github.com/Falieson/react-asteroid-meteor/commit/9ae4e4c05f1678fdea639506b3e1893735b8e01d

Also worked upgraded to 1.6-beta.18 so we can get node8
https://github.com/Falieson/react-asteroid-meteor/commit/da69704caf36bab3b5bd6c0992e9abf0ea419b8e

**Comment by holmrenser** [comment]
@hatelove85911 you can get the socket connection to work by specifying what websocket library to use, see #121

**Comment by hatelove85911** [comment]
Hi, I've made my code working. I've made some mistake with the SocketConstructor.  The platform I'm using is not web browser, so I've to make the SocketConstructor myself.
