### ISSUE TITLE
Error 404 "Method login not found"

### ISSUE THREAD

**Issue by ProphetDaniel** [mondora/asteroid#129]
I'm using asteroid in this [project](https://github.com/ProphetDaniel/meteor-drizzle). When clicking on Login button, the following error is triggered:

`{isClientSafe: true, error: 404, reason: "Method 'login' not found", message: "Method 'login' not found [404]", errorType: "Meteor.Error"}`

It really looks there is something Asteroid is doing wrong or reporting wrong.

**Comment by dimofte** [comment]
you need to add [Accounts](https://docs.meteor.com/api/accounts.html) to your [backend](https://github.com/ProphetDaniel/meteor-drizzle/blob/master/backend/.meteor/packages), user management is not part of Meteor's core

**Comment by ProphetDaniel** [comment]
Thank you @dimofte . With your help I was able to make it work.
