### ISSUE TITLE
API change suggestion

### ISSUE THREAD

**Issue by pscanf** [mondora/asteroid#21]
Use `find` instead of `reactiveQuery`, and return a cursor with `fetch` and `observe` methods.

**Comment by navinSing** [comment]
HI pscanf,, any updates on this ..

**Comment by navinSing** [comment]
@pscanf .. can we have a call to discuss how this issue can be resolved .. 

Thanks

**Comment by pscanf** [comment]
Sure, as I said in another issue, I'm currently in the process of doing a bit of refactor, so it's the right time to make suggestions. Feel free to schedule a hangout, and I'll try to be there. :-)

(I live in Europe)

**Comment by navinSing** [comment]
tomorrow 18th feb: 2 pm GMT ?  will catch you on hangout : paolo.scanferla@gmail.com

**Comment by pscanf** [comment]
Sounds good :smiley: . I have a sprint planning meeting tomorrow, but by that time I should be free. If for any reason I can't make it I'll let you know.

See you tomorrow then :smiley:

**Comment by pscanf** [comment]
Wontfix in `~0.6.0`, look forward for upcoming changes
