### ISSUE TITLE
Support for Observe API

### ISSUE THREAD

**Issue by gabrielstuff** [mondora/asteroid#23]
Hi !
The whole stuff is a really nice package and a great work. I'm already enjoying it using it.
What do you think about implementing 'observe' -> http://docs.meteor.com/#observe

The meteor-ddp package support it : https://github.com/eddflrs/meteor-ddp.

The implementation looks pretty straightforward : 

https://github.com/eddflrs/meteor-ddp/blob/master/meteor-ddp.js#L153
and 
https://github.com/eddflrs/meteor-ddp/blob/master/meteor-ddp.js#L212

So what do you think about it ?

**Comment by foobarbecue** [comment]
I would find this very useful.

**Comment by pscanf** [comment]
Wontfix. [`1.0.0`](https://github.com/mondora/asteroid/tree/1.0.0-rewrite) brings the possibility to mixin functionalities into Asteroid. It should be very easy to implement it that way.
