### ISSUE TITLE
LoginWithFacebook Error

### ISSUE THREAD

**Issue by toprakdeviren** [mondora/asteroid#30]
When i try login with facebook it gives me, "Uncaught TypeError: Cannot read property 'reactiveQuery' of undefined "

**Comment by foobarbecue** [comment]
I'm debugging my app which has included asteroid.chrome.js and facebook-login.js in Chrome dev tools. Asteroid.loginWithFacebook is undefined. Sounds like toprakdeviren explains the error in the asteroid code above? I'd like to dig in but don't understand how the plugins work.

**Comment by foobarbecue** [comment]
I've got the same problem:

<pre>Uncaught TypeError: Cannot read property 'reactiveQuery' of undefinedasteroid.chrome.js:788
 Asteroid._getOauthClientIdfacebook-login.js:16
 getFacebookOauthOptionsfacebook-login.js:29
 Asteroid.loginWithFacebookinject.js:25 initinject.js:117
 (anonymous function)</pre>

**Comment by foobarbecue** [comment]
I just checked, and I do have a collection in my database called meteor_accounts_loginServiceConfiguration . I added a line 
 this.getCollection("meteor_accounts_loginServiceConfiguration"); at asteroid.chrome.js:787 so that the local representation of the collection gets created. However, the ReactiveQuery is not returning any results. I have noticed that my ReactiveQueries don't return any results, but if I add a handler using .add() then I can get the data from the server collections.

**Comment by pscanf** [comment]
Mmh, if you post a snippet of code I can probably pinpoint the issue more precisely, but I have a theory. :-)
A collection gets created automatically when one of its element gets sent to the client. It might be that when you're calling `loginWithFacebook` "too early". You should at least wait for the DDP session to have started (listen to the `connected` event of the Asteroid instance). After that, collection elements will be sent by the server, so you can start using them. Elements from the `meteor_accounts_loginServiceConfiguration` collection are sent when you subscribe to `meteor.loginServiceConfiguration`, which asteroid does automatically for you. You'll have the guarantee that you have the service configurations on the client when that subscription is signaled by the server as `ready`. For that, subscriptions in Asteroid have a `ready` property, which is a promise that is resolved when the ready signal is received. So, to give a code example, you could try:

```js
myAsteroidInstance.on("connected", function () {
    // Asteroid doesn't expose the subscription directly. Fortunately, subscription calls are memoized
    // so you can safely call the subscribe method multiple times and it'll always return the same object
    myAsteroidInstance.subscribe("meteor.loginServiceConfiguration").ready.then(function () {
        myAsteroidInstance.loginWithFacebook();
    });
});
```

Hope this helps. :-)

**Comment by foobarbecue** [comment]
@pscanf, yep, that was exactly the problem, thanks! My new problem is that I don't have access to chrome.tabs because I'm in a content script in a Chrome extension. Tempted to try and write something that uses a popunder instead of a popup for login, but I'll probably just end up moving the login part to a background script instead.

**Comment by pscanf** [comment]
Oh right! That was the other thing I wanted to say! :smile: 

[Take a look at this code](https://github.com/mondora/asteroid-todo/tree/master/chrome-todo), it's a sample chrome extension implementation which should work.

**Comment by pscanf** [comment]
To expand on that a little, basically I don't login from the content script. Rather I message the background tab that I want to login, and the background tab initiates the dances.

**Comment by pscanf** [comment]
Which is exactly your proposed approach. I should read more carefully. :smile: (Pardon me, it's bedtime here, my disattention is caused by sleepiness :stuck_out_tongue: )

**Comment by pscanf** [comment]
Also, [from this code](https://github.com/mondora/asteroid-todo/blob/master/chrome-todo/app/background.js) it seems you can forego waiting for the `connected` events, as asteroid will queue the subscription call until the connection is established. Who knew! :smile:

**Comment by foobarbecue** [comment]
Awesome, I think you just saved me hours of head scratching. I'll try and submit some useful code to asteroid one of these days in return, once my app is up and running. ps- you must be excited about Dawn getting to Ceres!

**Comment by pscanf** [comment]
No problem, always happy to help! :smiley:

Eh eh, this days I was like "Yeah! Everyone's talking about Asteroid and Ceres! Oh, wait. Nevermind..." :smile:

**Comment by foobarbecue** [comment]
FYI I still haven't quite gotten login to work from the background script. I'm watching what's going on server-side with node-inspector. The server renders a login success response page with credentials and a function to store them in localStorage. I guess it's failing to store these, because in chrome dev tools my local storage for the background script context stays empty.

I will probably try putting something in the catch () here to debug this, but I'm going to lunch for a while and thought maybe you have a magic bullet for this!

I haven't actually tried running your asteroid version of todo yet.

```
<html>
<head>
<script type="text/javascript">

function storeAndClose() {

  var config = JSON.parse(document.getElementById("config").innerHTML);

  if (config.setCredentialToken) {
    var credentialToken = config.credentialToken;
    var credentialSecret = config.credentialSecret;

    if (config.isCordova) {
      var credentialString = JSON.stringify({
        credentialToken: credentialToken,
        credentialSecret: credentialSecret
      });

      window.location.hash = credentialString;
    }

    if (window.opener && window.opener.Package &&
          window.opener.Package.oauth) {
      window.opener.Package.oauth.OAuth._handleCredentialSecret(
        credentialToken, credentialSecret);
    } else {
      try {
        localStorage[config.storagePrefix + credentialToken] = credentialSecret;
      } catch (err) {
        // We can't do much else, but at least close the popup instead
        // of having it hang around on a blank page.
      }
    }
  }

  if (! config.isCordova) {
    document.getElementById("completedText").style.display = "block";
    window.close();
  }
}
</script>
</head>
<body onload="storeAndClose()">
  <p id="completedText" style="display:none;">
    Login completed. <a href="#" onclick="window.close()">
      Click here</a> to close this window.
  </p>

  <div id="config" style="display:none;">{"setCredentialToken":true,"credentialToken":"XXX","credentialSecret":"XXX","storagePrefix":"Meteor.oauth.credentialSecret-","isCordova":false}</div>
</body>
</html>
```

**Comment by pscanf** [comment]
Try adding the `mondora:asteroid`  package to the meteor app.

**Comment by pscanf** [comment]
I can't believe I haven't put it into the documentation yet. I really need to give more attention to this library! (We're using in production in ~5 projects and all, so it's not abandoned, but I haven't really put enough effort in documenting it properly, writing examples etc).

**Comment by foobarbecue** [comment]
Hm, tried adding it and there was no change.

**Comment by pscanf** [comment]
Mmh, I can't really tell what could be causing the issue. I can help you via hangout if you want.

**Comment by foobarbecue** [comment]
pscanf helped me via Facebook. The problem was lack of permissions! I needed to add permissions to activeTab and tabs in my manifest.json. I guess this isn't exactly @toprakdeviren 's problem, but mine is solved now.
