### ISSUE TITLE
Expose miniMongo and Meteor api the same way they are in the Meteor app

### ISSUE THREAD

**Issue by dotnetwise** [mondora/asteroid#31]
So you don't have to learn/do stuff differently.

They should be transparent, although what the functions return might be wrapped with more compatibility stuff.

**Comment by pscanf** [comment]
Wontfix. With the mixin api in [`1.0.0`](https://github.com/mondora/asteroid/tree/1.0.0-rewrite) it should be easy to make a mixin which replicates the Meteor api.
