### ISSUE TITLE
Query not working on data change for boolean?

### ISSUE THREAD

**Issue by willoughby** [mondora/asteroid#38]
I have a query like notifications.reactiveQuery({"read":false}), which returns records fine, when a record read attr changes to true (via a meteor.call 'clearNotification'), the query doesn't seem to catch the change. my current workaround is to rerun the query in the updated promise from my meteor.call method

I can tweak the read attr in the db and it works as you expect. not sure if its something i'm missing ?
```
var unreadNotificationQuery = notifications.reactiveQuery({"read":false});
  unreadNotificationQuery.on('change',function (change) {   
    console.log("change")
    $scope.notifications =  unreadNotificationQuery.result
    $scope.$apply()
  }) 

$scope.clearNotification = function(notification) {
    call = meteor.call('clearNotification',notification._id);    
    call.updated.then(function(){
      var q = notifications.reactiveQuery({"read":false});      
      $scope.notifications =  q.result 
      $scope.$apply() 
    })
  }
```

**Comment by pscanf** [comment]
Was it solved? Closing for cleanup, reopen if necessary.
