### ISSUE TITLE
Communicate login information

### ISSUE THREAD

**Issue by bernatfortet** [mondora/asteroid#42]
Hi, 

I have a chrome extension that uses Twitter Sign in.
Also, I have a Meteor client that uses Twitter Sign in.

How can I sign in once and affect the other?

eg. I login on the meteor client and now the chrome extension is also logged.

Thank you.

**Comment by pscanf** [comment]
Hello Bernat :-),

It should be possible, theoretically, but Asteroid doesn't offer the functionality (yet :-) ).

Upon login, meteor stores your login information in `localStorage`:

- `Meteor.loginToken`
- `Meteor.loginTokenExpires`
- `Meteor.userId`

A similar thing is done by Asteroid, which stores the login token in `multiStorage`, an abstraction over the various implementations of `localStorage` available for different platforms (in the chrome extensions platform it uses `chrome.storage.local`):

- `{protocol}://{host}__{instanceId}__login_token_`, for example `https://api.mondora.com__0__login_token__`

If you keep the two "storages" in sync, once you login somewhere, you're logged in everywhere.
The "theoretically possible" refers to keeping the two storages in sync. I suppose you could do something like:

- before logging in with the extension, open your Meteor website in a new tab
- check if the token is present in `localStorage`
- if it is, retrieve it and login directly with it
- else, complete the login procedure and, upon login, inject the newly acquired token into the website's `localStorage`

Let me know how it goes. :-)

Cheers

**Comment by bernatfortet** [comment]
Thanks!
