### ISSUE TITLE
LoginWith * Redirects do not work (Chrom Extension)

### ISSUE THREAD

**Issue by bernatfortet** [mondora/asteroid#43]
For some reason I can't make Facebook or Twitter Login to work on my chrome extension

``` coffeescript
		this.ddp = new Asteroid("localhost:3000");


		this.ddp.on('connected', =>
			console.log 'Connected'


			this.ddp.resumeLoginPromise.then( ->
				console.log ('ok')
			).fail( =>
				console.log 'fail, now log in'

				this.ddp.subscribe("meteor.loginServiceConfiguration").ready.then =>
					#this.ddp.loginWithTwitter()
					this.ddp.loginWithFacebook()
			)
		)

```

This sends me to an endlessly loading new tab.

The following images are the callback urls for the facebook and twitter apps.
![screen shot 2015-02-09 at 11 00 05 am](https://cloud.githubusercontent.com/assets/390010/6113268/d52bb248-b04a-11e4-9402-1a12e730fb23.png)
![screen shot 2015-02-09 at 11 00 10 am](https://cloud.githubusercontent.com/assets/390010/6113267/d52ae868-b04a-11e4-823f-2078c9f41a17.png)

Any idea on why is this happening? 

Thanks.

**Comment by bernatfortet** [comment]
I'm getting this error from the server.
![screen shot 2015-02-10 at 9 16 22 pm](https://cloud.githubusercontent.com/assets/390010/6142373/2044dbb8-b16a-11e4-8d36-a1ce1e296550.png)

**Comment by pscanf** [comment]
Hi Bernat,

Sorry for the late reply, I've had some busy days. :-)

I think I saw that error before, but I can't remember exactly when or where. How about a hangout to figure it out? (I'm finding google hangouts a much quicker way to solve issues, it takes me forever to type :-D )

Let me know
Cheers!

**Comment by pscanf** [comment]
Fixed via hangout iirc. Reopen if necessary. :smiley:

**Comment by bernatfortet** [comment]
@pscanf hello Paolo. I was wondering if we could have another hangout to dicuss this. I've had some time to look into it again. 
Thanks in advance for your time!

Bernat.

**Comment by AayushShrestha** [comment]
@pscanf @bernatfortet Hello Guys.

I am trying to use asteroid-oauth-mixin to make google login in my extension that connects with my meteor app. I was able to get the login popup. After I select an account, the popup goes blank. Can you guys please help me?
