### ISSUE TITLE
 onReady/onError callback in a subscription 

### ISSUE THREAD

**Issue by navinSing** [mondora/asteroid#45]
How do we handle the onReady/onError callback in a subscription ?   Asteroid.subscribe(name,arg, { onReady: ...   

callbacks Function or Object
Optional. May include onError and onReady callbacks. If a function is passed instead of an object, it is interpreted as an onReady callback.

http://docs.meteor.com/#/full/meteor_subscribe

**Comment by pscanf** [comment]
The `Asteroid.subscribe` method returns a subscription instance, which has a property `ready`, a promise which is fulfilled "on ready", and rejected "on error".

[More details here.](https://github.com/mondora/asteroid#asteroidsubscription)

Cheers!
