### ISSUE TITLE
Refactor calls

### ISSUE THREAD

**Issue by navinSing** [mondora/asteroid#46]
Refactor Calls  : Can we write the code for calls/loginWith etc to be similar to meteor .. which takes a callback .. rather than returning the promise. Its same .. but keeping api similar makes life simpler

**Comment by pscanf** [comment]
Hello there,

I'm actually in the process of refactoring Asteroid a bit, but I'm not sure about adding this possibility. I thought about it in the past, but I wouldn't want to complicate the code too much (I definitely want to keep promises, so I would need to support both patterns). But maybe it won't, I guess I'll find out while writing it :-) . Anyway, thanks for the feedback, I'll definitely keep this use case in mind while refactoring, and I'll let you know as soon as I make up my mind. :-)

Cheers
