### ISSUE TITLE
Session variables

### ISSUE THREAD

**Issue by navinSing** [mondora/asteroid#47]
Can we have a hook to store and retrieve session variables.

http://docs.meteor.com/#/full/session_set

**Comment by pscanf** [comment]
Hello again (I'm in issue-answering mode ;-) ),

I'm afraid this functionality, and also the tracker functionality in issue #48 , are outside the scope of Asteroid, which only aims to be a way to connect to a Meteor backend, and not a full reactive client-side framework.

Usually frameworks such as Angular or Ember have libraries that allow such things, so I'd suggest using those. :-)

Cheers
