### ISSUE TITLE
Tracker and dependency

### ISSUE THREAD

**Issue by navinSing** [mondora/asteroid#48]
Hi, 

can we create tracker over  the variables and define dependencies between them .. 

like : http://docs.meteor.com/#/full/tracker_dependency

**Comment by chicagogrooves** [comment]
This project (which has complementary aims to Asteroid), bundles up Tracker: http://bit.ly/mini-meteor

**Comment by navinSing** [comment]
@chicagogrooves  .. Thanks

Does it cover find() #21

**Comment by navinSing** [comment]
Also can it connect to the remote meteor server.

**Comment by pscanf** [comment]
See issue #47 :-)
