### ISSUE TITLE
Status indicator on subscription download

### ISSUE THREAD

**Issue by Compy** [mondora/asteroid#53]
Is there any way to get feedback on whether or not a subscription is still loading documents? I'm using this on a mobile application and would love to display a loading icon while records are still loading. Great work, by the way!

**Comment by pscanf** [comment]
Hi there. :-)

Yes, there is. A subscription instance (the thing returned by `subscribe`, which acts more or less as a factory) has a `ready` property, which is a promise, that gets resolved when the initial batch of documents has loaded, so you can use that.

Cheers
