### ISSUE TITLE
Consider using Promiz instead of Q

### ISSUE THREAD

**Issue by dandv** [mondora/asteroid#67]
[Promiz](https://github.com/Zolmeister/promiz) is much smaller, [Promise/A+ compatible](https://github.com/Zolmeister/promiz/issues/2), and [written by a super smart guy](https://www.crunchbase.com/person/zoli-kahan). It's also [used by Webix](http://docs.webix.com/helpers__ajax_operations.html#promiseapiforajaxrequests).

This would shave off 50KB!

**Comment by pscanf** [comment]
Hey @dandv,

I took a look at [promiz](https://github.com/Zolmeister/promiz) and tried testing it with [this promise test suite](https://github.com/promises-aplus/promises-tests), but it doesn't seem to be compliant.

Actually I was considering using [es6-promise](https://github.com/jakearchibald/es6-promise), which is also much smaller than Q and seems to be embedded in a lot of libraries. What do you think of it?

Thanks (and sorry for taking so long to reply!)

**Comment by dandv** [comment]
Interesting. I was thinking @Zolmeister addressed that with https://github.com/Zolmeister/promiz/issues/2#issuecomment-31632489.

I've seen es6-promise recommended as *the* polyfill, so it should be a good choice.

**Comment by Zolmeister** [comment]
Either option is fine. Promiz is `0.89kb` (min+gz), while es6-promise is `2.13kb` (min+gz)
As for running the Promiz tests, `npm run all` should do it ((package.json)[https://github.com/Zolmeister/promiz/blob/master/package.json])

**Comment by pscanf** [comment]
Ah I see, I guess I run them against the "unadapted" version, my bad, sorry.

Very well then, I might be able to do something about it tomorrow, as I need to do some long due refactoring before including it in a new project I'm working on.

I'll keep you posted :smiley: 
Cheers

**Comment by tomByrer** [comment]
I would slightly prefer a more universal ES6 promise, but doesn't matter too much.

**Comment by pscanf** [comment]
At the end for [`1.0.0`](https://github.com/mondora/asteroid/tree/1.0.0-rewrite) I went with the polyfill included by babel.

**Comment by dandv** [comment]
How about for `asteroid.chrome.js`? [Chrome has Promise support in its ES6 implementation](https://kangax.github.io/compat-table/es6/#Promise_basic_functionality).

**Comment by pscanf** [comment]
I published `2.0.0` a few days ago, and getting around solving some issues. :smiley: 

`2.0.0` assumes there's a `Promise` global class available. So well, it shouldn't be a problem polyfilling (if necessary) it with whatever library one prefers, be it [promiz](https://github.com/Zolmeister/promiz) or babel's one.

Cheers :smiley:
