### ISSUE TITLE
how to connect to meteor.com deployment

### ISSUE THREAD

**Issue by stlouisweb** [mondora/asteroid#68]
How can one connect asteroid to a deployed instance of meteor (not localhost).

I've tried
 var ceres = new Asteroid("dmyapp.meteor.com:3000"); 

the websocket never connects.

what am I doing wrong?

**Comment by stlouisweb** [comment]
Got it using a secure connection:
```javascript
var ceres = new Asteroid("myapp.meteor.com:443", true);
```

**Comment by pscanf** [comment]
Glad it solved itself :smiley:

You may also need to use [mondora/mondora-asteroid](https://github.com/mondora/mondora-asteroid) to set cross-origin headers and make asteroid work with oauth login services.

Cheers
