### ISSUE TITLE
What's the deal with asteroid.browser on npmjs?

### ISSUE THREAD

**Issue by dandv** [mondora/asteroid#70]
I found this package published by @endows, https://www.npmjs.com/package/asteroid.browser

Are they associated with the project? Hey @endows, can you please update the README of [your fork](https://github.com/endows/asteroid) and point package.json to your repo? (Sorry I couldn't file an issue there - issues are disabled by default in forks)

Also, do we really need a separate package?

**Comment by endows** [comment]
No. This repo is to private. What do you want ? Delete it?
I'll not delete it.

**Comment by dandv** [comment]
Hi @endows, looks like there's a language/culture clash/barrier here. Please try to be nicer. The Meteor community has traditionally been a welcoming place; let's keep it that way.

So the npm package https://www.npmjs.com/package/asteroid.browser is public, because I and others can see it, and it appears in [search results for asteroid](https://www.npmjs.com/search?q=asteroid).

Your fork (GitHub repo) is also public - https://github.com/endows/asteroid.

Do you mean that you want this package to be used only privately by you? In that case, you might want to obtain a private npm modules account - https://www.npmjs.com/private-modules.

I would like to understand what the motivation was for creating this npm package, given that the file you need from it, `asteroid.browser.js`, already exists in the official Asteroid npm package published by @pscanf.

I would also like to respectfully ask that, if you really want to keep this package on npm, to mention that it's a fork of the original, credit its author (@pscanf), and mention how your fork is different from the original.

Nothing out of the ordinary; just common sense courtesy in the open source world.

**Comment by dandv** [comment]
PS @endows: the website you're listing on your GitHub profile, http://endows.tk, seems infected by malware because it tries to trick me to install some fake Windows drivers. Maybe your GitHub account has been hacked?

**Comment by endows** [comment]
http://endows.tk is haked. but github account is not haked.

asteroid.browser is made for browser.When using browserify,```mondora/asteroid``` is not work.because ```package.json```'s main path is ```"dist/asteroid.node.js"```.
``` asteroid.browser ```'s main path is  ```"dist/asteroid.browse.js"```

This is very important package.
I'll not delete it.If there is a complaint,Litigate it.
http://www.icj-cij.org/homepage/

**Comment by dandv** [comment]
> I'll not delete it.If there is a complaint,Litigate it.
> http://www.icj-cij.org/homepage/

LOL.

Okay, I give up :)

PS: http://blog.codinghorror.com/the-ugly-american-programmer/
