### ISSUE TITLE
Uncaught Error: process.binding is not supported

### ISSUE THREAD

**Issue by mkolodny** [mondora/asteroid#71]
I'm seeing the error `"Uncaught Error: process.binding is not supported"` when attempting to `require 'asteroid'` using [browserify](http://browserify.org/).

It appears that the problem is in `faye-websocket`. Browserify uses the [process](https://www.npmjs.com/package/process) package to mimic to Node's built-in `process` module. The `process` module doesn't shim the `binding` method, which is causing the error I'm seeing. This issue goes away when I replace `faye-websocket` with the [websocket](https://www.npmjs.com/package/websocket) package. 

I'm going to submit a pull request that uses the more popular websocket package instead of faye-websocket.

**Comment by mkolodny** [comment]
Using `websocket` instead of `faye-websocket`, I'm now seeing the error `TypeError: this._SocketConstructor is not a function`. I see the same error if I use `dist/asteroid.browser.js` instead of `dist/asteroid.node.js`.

**Comment by mkolodny** [comment]
I'm now seeing the error `TypeError: this._SocketConstructor is not a function` when requiring `asteroid` in my karma tests after the update. I also see this error if I use `dist/asteroid.browser.js` instead of `dist/asteroid.node.js`.

Any advice for using asteroid with karma/browserify?

**Comment by mkolodny** [comment]
I ended up getting this to work by installing [SockJS], and using `dist/asteroid.browser.js`.

**Comment by MHerszak** [comment]
Hi, just for future reference.. The fs module will not work on the client. You should move file access to a place that is server only. That worked for me.
