### ISSUE TITLE
Add polymer component

### ISSUE THREAD

**Issue by alexzaporozhets** [mondora/asteroid#73]
Hi, I think it would be good to have a ready solution for Polymer.

**Comment by pscanf** [comment]
Hi @alexzaporozhets . Would definitely be useful, but I think it'd make more sense to have it in a separate library which relies on Asteroid. I'm not familiar with polymer, so I'm afraid I can't be of much help. If you do develop or come across a Asteroid polymer component let me know and I'll sure mention it in the readme!
