### ISSUE TITLE
Not Working When accessing Server in Different Host

### ISSUE THREAD

**Issue by radiegtya** [mondora/asteroid#81]
var ddp = new Asteroid("my-meteor-on-digitalocean.com");

```
subscribe etc not working
```

Please help

**Comment by davidebianchi** [comment]
Hi @radiegtya, it might be a cross-origin communication issue. You can try to add in your meteor project the `mondora:asteroid` package, which allows cross-origin communication (configurable via environment variables).

**Comment by radiegtya** [comment]
@davidebianchi : thanks david, I'll try that ASAP. :100:

**Comment by radiegtya** [comment]
@davidebianchi : 
I've tried adding mondora:asteroid + setting up the ALLOWED_ORIGIN environment var from mup.json (because I am deploying my meteor apps using MUP) to : * (to allow access from every host)

but still not working. Any Idea about this?

**Comment by fermuch** [comment]
do you have websockets enabled? For example, with the free layer of cloudflare SSL (only business users can SSL on websockets) we have to disable websockets. Is this your case?

**Comment by radiegtya** [comment]
Have found the solution. In Mup add environment with name server of current server. Then add asteroid plugin.
